

aa2codon =  {'phe' : ['ttt','ttc'] ,
            'leu' : ['tta','ttg','ctt','ctc','cta','ctg'],
            'ile' : ['att','atc','ata'],
            'met' : ['atg'],
            'val' : ['gtt','gtc','gta','gtg'],
            'ser' : ['tct','tcc','tca','tcg','agt','agc'],
            'pro' : ['cct','ccc','cca','ccg'],
            'thr' : ['act','acc','aca','acg'],
            'ala' : ['gct','gcc','gca','gcg'],
            'tyr' : ['tat','tac'],
            'stop': ['taa','tag','tga'],
            'his' : ['cat','cac'],
            'gln' : ['caa','cag'],
            'asn' : ['aat','aac'],
            'lys' : ['aaa','aag'],
            'asp' : ['gat','gac'],
            'glu' : ['gaa','gag'],
            'cys' : ['tgt','tgc'],
            'trp' : ['tgg'],
            'arg' : ['cgt','cgc','cga','cgg','aga','agg'],
            'gly' : ['ggt','ggc','gga','ggg'] }


codon2aa =  { 'aaa' : 'lys',
            'aag' : 'lys',
            'tta' : 'leu',
            'ttg' : 'leu',
            'ctt' : 'leu',
            'ctc' : 'leu',
            'cta' : 'leu',
            'ctg' : 'leu',
            'gaa' : 'glu',
            'gag' : 'glu',
            'caa' : 'gln',
            'cag' : 'gln',
            'cat' : 'his',
            'cac' : 'his',
            'aat' : 'asn',
            'aac' : 'asn',
            'tct' : 'ser',
            'tcc' : 'ser',
            'tca' : 'ser',
            'tcg' : 'ser',
            'agt' : 'ser',
            'agc' : 'ser',
            'cgt' : 'arg',
            'cgc' : 'arg',
            'cga' : 'arg',
            'cgg' : 'arg',
            'aga' : 'arg',
            'agg' : 'arg',
            'tgg' : 'trp',
            'gct' : 'ala',
            'gcc' : 'ala',
            'gca' : 'ala',
            'gcg' : 'ala',
            'tgt' : 'cys',
            'tgc' : 'cys',
            'ggt' : 'gly',
            'ggc' : 'gly',
            'gga' : 'gly',
            'ggg' : 'gly',
            'gat' : 'asp',
            'gac' : 'asp',
            'ttt' : 'phe',
            'ttc' : 'phe',
            'atg' : 'met',
            'tat' : 'tyr',
            'tac' : 'tyr',
            'gtt' : 'val',
            'gtc' : 'val',
            'gta' : 'val',
            'gtg' : 'val',
            'act' : 'thr',
            'acc' : 'thr',
            'aca' : 'thr',
            'acg' : 'thr',
            'cct' : 'pro',
            'ccc' : 'pro',
            'cca' : 'pro',
            'ccg' : 'pro',
            'att' : 'ile',
            'atc' : 'ile',
            'ata' : 'ile',
            'taa' : 'stop',
            'tag' : 'stop',
            'tga' : 'stop' }





if __name__ == '__main__':
    pass

